#!/bin/bash

#Working on it...
#Sorry, but I started doing this in the afeternoon and suddenly it's after midnight...someone's it playing with the clocks
#I'll try to deliver the scripts tomorrow...or not...